"""Turns config/features.yaml into the concrete column list used to build
X for training.

Note on scope: every remaining feature in this dataset is numeric and gets
the same RobustScaler treatment (see models.py), so there's no need for a
per-column sklearn ColumnTransformer here -- that would be complexity with
no behavioral payoff. If a future feature set mixes numeric and categorical
columns needing different preprocessing, that's when introducing a
ColumnTransformer earns its keep; don't add it preemptively.
"""

from __future__ import annotations

import pandas as pd

from housing_ml.config import FeaturesConfig


def selected_columns(features_config: FeaturesConfig, df: pd.DataFrame) -> list[str]:
    """Return the feature columns to train on, validated against what's
    actually present in the dataframe.

    Raising here (rather than silently ignoring a missing column) matters
    because config/features.yaml is meant to be regenerated by
    scripts/select_features.py against a specific data snapshot -- if the
    raw data later loses a column that config still references, that's a
    real inconsistency worth failing loudly on.
    """
    missing = [c for c in features_config.selected if c not in df.columns]
    if missing:
        raise ValueError(
            f"config/features.yaml lists column(s) not present in the data: {missing}. "
            "Re-run `make select-features` to regenerate it against the current data."
        )
    return list(features_config.selected)
